#!/bin/bash

#SBATCH --job-name=star-align
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=0:50:00
#SBATCH --mem=40G

set -eux

module load cellranger/2.1.0
module load samtools/1.10

PATH=/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cellranger/2.1.0/STAR/5dda596/:$PATH

THREADS=$SLURM_CPUS_PER_TASK

NAME=$1; shift
INDEX=$1; shift
OUTDIR=$1; shift
R1=$1;shift
R2=$1

rsync -v $R1 ${SLURM_TMPDIR}
rsync -v $R2 ${SLURM_TMPDIR}

mkdir -p ${SLURM_TMPDIR}/$NAME && cd ${SLURM_TMPDIR}/$NAME

STAR --runMode alignReads \
    --runThreadN $THREADS \
    --genomeDir $INDEX \
    --readFilesIn <(zcat $R1) <(zcat $R2) \
    --outFilterType BySJout \
    --outFilterMultimapNmax 20 \
    --alignSJoverhangMin 8 \
    --alignSJDBoverhangMin 1 \
    --outFilterMismatchNmax 999 \
    --outFilterMismatchNoverReadLmax 0.04 \
    --alignIntronMin 20 \
    --alignIntronMax 1000000 \
    --alignMatesGapMax 1000000 \
    --outSAMtype BAM SortedByCoordinate

# default output bam name is Aligned.sortedByCoord.out.bam
samtools index Aligned.sortedByCoord.out.bam

rsync -rvz ${SLURM_TMPDIR}/$NAME $OUTDIR
